{% set name = "scikits-bootstrap" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/f0/a1/f1060d5d2d1e74816b39813f640526dcdd194ce59dc8b4c4227fe0832714/scikits_bootstrap-{{ version }}.tar.gz"
  sha256: 6942bddee6ca1818499c3c7d945974fe5f6cf6116a707bd1df4c81c57849c905

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pyerf
    - python >=3.6
    - setuptools

test:
  imports:
    - scikits
    - scikits.bootstrap

about:
  home: "http://github.com/cgevans/scikits-bootstrap"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Bootstrap confidence interval estimation routines for SciPy"
  doc_url: https://github.com/cgevans/scikits-bootstrap
  dev_url: https://github.com/cgevans/scikits-bootstrap

extra:
  recipe-maintainers:
    - cgevans
    - tnigon
