{% set name = "scikits-bootstrap" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/24/55/3f9953f56ccf8ad89f11cde928e2b6bcd073bf6109a5f5c4d68ff9993873/scikits.bootstrap-1.1.0.tar.gz"
  sha256: 6ab95d3a7e607731433e97cfd499fcd2da52f065aaae8d0156367904c7dfd1cf

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pyerf
    - python >=3.6
    - setuptools

test:
  imports:
    - scikits
    - scikits.bootstrap

about:
  home: "http://github.com/cgevans/scikits-bootstrap"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Bootstrap confidence interval estimation routines for SciPy"
  doc_url: https://github.com/cgevans/scikits-bootstrap
  dev_url: https://github.com/cgevans/scikits-bootstrap

extra:
  recipe-maintainers:
    - cgevans
    - tnigon
